# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        word sense disambiguation: 3
        parsing: 3
        bert: 3
        semantic analysis: 3
        natural language understanding: 3

# 通知の閾値
score_threshold: 0
